# Created using wingetcreate 1.2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.4.0.schema.json

PackageIdentifier: StaticalApS.PrismforALStandardEdition(SE)
PackageVersion: 2.2.0.6
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.4.0
